export const ADD_TRANSACTION_REQUEST = "ADD_TRANSACTION_REQUEST";
export const ADD_TRANSACTION_SUCCESS = "ADD_TRANSACTION_SUCCESS";
export const ADD_TRANSACTION_FAILURE = "ADD_TRANSACTION_FAILURE";

export const GET_TRANSACTIONS_REQUEST = "GET_TRANSACTIONS_REQUEST";
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS";
export const GET_TRANSACTIONS_FAILURE = "GET_TRANSACTIONS_FAILURE";

export const GET_DEBIT_TRANSACTIONS_REQUEST = "GET_DEBIT_TRANSACTIONS_REQUEST";
export const GET_DEBIT_TRANSACTIONS_SUCCESS = "GET_DEBIT_TRANSACTIONS_SUCCESS";
export const GET_DEBIT_TRANSACTIONS_FAILURE = "GET_DEBIT_TRANSACTIONS_FAILURE";

export const GET_CREDIT_TRANSACTIONS_REQUEST = "GET_CREDIT_TRANSACTIONS_REQUEST";
export const GET_CREDIT_TRANSACTIONS_SUCCESS = "GET_CREDIT_TRANSACTIONS_SUCCESS";
export const GET_CREDIT_TRANSACTIONS_FAILURE = "GET_CREDIT_TRANSACTIONS_FAILURE";